apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greeter-controller-rolebinding
subjects:
  - kind: ServiceAccount
    name: greeter-controller
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: greeter-controller-role
