apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appdeployment-controller-rolebinding
subjects:
  - kind: ServiceAccount
    name: appdeployment-controller
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appdeployment-controller-role
