// This file contains DeepCopy methods required by the runtime.Object interface.
//
// In real projects these are auto-generated by running:
//   make generate   (which calls controller-gen)
//
// We write them by hand here so the generated magic is visible and
// you can understand what it does.
//
// Every type that is registered with the Scheme must implement runtime.Object,
// which requires a DeepCopyObject() method. DeepCopy ensures that when the
// cache makes a copy of your object, fields like maps and slices are properly
// cloned rather than sharing the same underlying memory.
package v1

import runtime "k8s.io/apimachinery/pkg/runtime"

// ---------- HelloWorld ----------

// DeepCopyInto copies all fields from in into out.
// For types with only value fields (strings, ints, nested structs that are
// also value types) a simple struct assignment (*out = *in) is enough.
// ObjectMeta contains maps and slices so we delegate its copy to the
// generated method on metav1.ObjectMeta.
func (in *HelloWorld) DeepCopyInto(out *HelloWorld) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta) // handles labels, annotations maps
	out.Spec = in.Spec                           // Spec contains only a string — safe to copy directly
	out.Status = in.Status                       // Status is empty — trivial copy
}

// DeepCopy creates a standalone deep copy of HelloWorld.
func (in *HelloWorld) DeepCopy() *HelloWorld {
	if in == nil {
		return nil
	}
	out := new(HelloWorld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object. This is what the Scheme and client
// cache call when they need a copy of your object.
func (in *HelloWorld) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ---------- HelloWorldList ----------

func (in *HelloWorldList) DeepCopyInto(out *HelloWorldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelloWorld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HelloWorldList) DeepCopy() *HelloWorldList {
	if in == nil {
		return nil
	}
	out := new(HelloWorldList)
	in.DeepCopyInto(out)
	return out
}

func (in *HelloWorldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
