apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-enforcer-controller-binding
subjects:
  - kind: ServiceAccount
    name: namespace-label-controller
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-enforcer-controller
